apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deployment
  namespace: converter-service
  labels:
    app: converter
spec:
  replicas: 1 # Good for high availability/throughput for a worker
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4 # Standard rolling update settings
  template:
    metadata:
      labels:
        app: converter
        service: converter-api # This label is important for the Service selector
    spec:
      containers:
        - name: converter-api # Container name
          image: hydjing/flask-kubernetes-converter # Your Docker image
          imagePullPolicy: Always # Good for development to ensure latest image
          envFrom:
            - configMapRef:
                name: converter-service-configmap # References your ConfigMap
            - secretRef:
                name: converter-secret # References your Secret