apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-configmap
  namespace: gateway-service
  labels:
    app: gateway                               
    service: gateway-api                       
    tier: backend                           
    environment: production                 
    project: flask-kubernetes
data:
  AUTH_SVC_ADDRESS: "auth:5000"