apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: gateway-service
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: gateway
        service: gateway-api
    spec:
      containers:
        - name: gateway-api
          image: hydjing/flask-kubernetes-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gateway-service-configmap
            - secretRef:
                name: gateway-secret